site_name: instantOS
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: assets/instantos.png
  features:
  - navigation.instant
  - navigation.tabs


markdown_extensions:
  - footnotes
  - toc:
          permalink: true
  - pymdownx.keys

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/paperbenni
    - icon: fontawesome/brands/github
      link: https://github.com/instantOS
    - icon: fontawesome/brands/discord
      link: https://discord.io/instantOS
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/instantOS/community?source=orgpage

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Basics:
    - Open applications: apps.md
    - Close applications: close.md
    - Shut down: shutdown.md
    - Shortcuts: shortcuts.md
    - Tags: tags.md
    - Layouts: layouts.md
    - Floating windows: tags.md
    - Audio: audio.md
    - Screenshots: screenshots.md

  - Extra features:
    - Overlays: overlays.md
    - Scratchpad: scratchpad.md
    - Alt-tab: alttab.md
    - Sticky windows: sticky.md
  - Power-User Features:
    - instantASSIST: instantassist.md
    - quickmenu: quickmenu.md
    - visibility options: visibility.md
    - customizing: customize.md
    - terminal: terminal.md

