site_name: instantOS
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: assets/instantos.png
  features:
    - navigation.instant
    - navigation.tabs

markdown_extensions:
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/paperbenni
    - icon: fontawesome/brands/github
      link: https://github.com/instantOS
    - icon: fontawesome/brands/discord
      link: https://discord.io/instantOS
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/instantOS/community?source=orgpage

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Basics:
      - Keybindings: hotkeys.md
      - Open applications: apps.md
      - Close applications: close.md
      - Shut down: shutdown.md
      - Shortcuts: shortcuts.md
      - Tags: tags.md
      - Layouts: layouts.md
      - Floating windows: tags.md
      - Audio: audio.md
      - Screenshots: screenshots.md
      - Updates: update.md
      - Fullscreen: fullscreen.md
  - Extra features:
      - File search: filesearch.md
      - Overlays: overlays.md
      - Scratchpad: scratchpad.md
      - Alt-tab: alttab.md
      - Sticky windows: sticky.md
      - Window drawing: drawing.md
      - Notification center: notify.md
  - Power-User Features:
      - instantASSIST: instantassist.md
      - Quickmenu: quickmenu.md
      - Visibility options: visibility.md
      - Customizing: customize.md
      - WM configuration: wmsettings.md
      - Terminal theming: terminaltheme.md
      - Menu configuration: menusettings.md
      - Terminal: terminal.md
  - Noob guides:
      - Vim bindings: vim.md
      - Installation: installguide.md
  - Gaming (WIP):
      - Beginners guide: gaming/gamebegin.md
      - Guide: gaming/gaming.md
  - Development:
      - ibuild dev tools: development/ibuild.md
      - status bar: development/status.md
      - instantMENU: development/instantMENU.md
      - instantARCH: development/instantARCH.md
